language: android
jdk: oraclejdk8
dist: trusty

env:
  global:

android:
  components:
    - tools
    - build-tools-24.0.1
    - android-29
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew

before_script:
  - chmod +x gradlew

#script:
#  - ./gradlew clean build
#  - ./gradlew test
